config/routes.rb
Bookmarks::Application.routes.draw do
<<<<<<< HEAD

  resources :registrations

  get "user/index"

  resources :login

  resources :administrators

resources :user

  get "home/index"

 resources :registrations do
 get "thanq", :on => :collection
  end

=======
<<<<<<< HEAD
=======

<<<<<<< HEAD
  resources :login

resources :administrators

resources :users

  get "home/index"

=======
  resources :registrations

  get "user/index"
>>>>>>> 5a795c21f7d78d8f21c6bd2902535dd2cd76bfec

  resources :login

  resources :administrators 

  resources :users

<<<<<<< HEAD
   get "home/index"
=======
>>>>>>> d4fc60e117b8ca30feced9b7b2fa0a42c9712216
 
 resources :registrations do
 get "thanq", :on => :collection
  end
<<<<<<< HEAD
 
=======
=======

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
 get "home/index"
>>>>>>> 5a795c21f7d78d8f21c6bd2902535dd2cd76bfec
 
 resources :registrations do
 get "thanq", :on => :collection
  end
<<<<<<< HEAD

=======
>>>>>>> 33974ae8361aa7be140ed58d918681e684cebaa1
>>>>>>> 43d6c49c433df6d816da9ee7945f8894f27353d0
>>>>>>> 78e96ad409b22ad63c71ab33320580c4a5c00ca8
>>>>>>> 3271831d142430af27be10ac9d061af528258ffa
>>>>>>> 5a795c21f7d78d8f21c6bd2902535dd2cd76bfec
>>>>>>> d4fc60e117b8ca30feced9b7b2fa0a42c9712216
>>>>>>> 4e9b5ba0a5ca01fe8b9652b3b61c260fc54a0cc3

  root :to => "home#index"

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/registration.rb
class Registration < ActiveRecord::Base
 
  validates :name, :presence => true,
                   :length   => {:minimum => 5 }
  
 
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  def index
  end

  def new
    @administrator = Administrator.new
  end

  def create
  end

  def update
  end

  def delete
  end

  def show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @total_bookmarks=Users.all
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
   @registration = Registration.all
  end
  def create
   @registration = Registration.new(params[:registration])
   @register = Registration.find_all_by_email(@registration.email)
   if(!@register.blank? && @register.first.password.eql?(@registration.password))
    session[:register] = @register.first.id
    flash[:notice] = "Logged in Successfully"
    redirect_to user_index_path
   else
    flash[:error] = "Failed to login"
    redirect_to home_index_path
   end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
  @registrations=Registration.all
  @registration=Registration.new

  end

  def new
<<<<<<< HEAD
@registration=Registration.new
=======
<<<<<<< HEAD
>>>>>>> ecf37fb366ee78729309aa32f602dad18c435902

   @registration=Registration.new

=======
>>>>>>> 5a795c21f7d78d8f21c6bd2902535dd2cd76bfec
  end

  def create
   if (params[:registration][:password] == params[:confirmpassword])
<<<<<<< HEAD
         @registration=Registration.new(:name => params[:registration][:name],:emailaddress => params[:registration][:emailaddress],:password => params         [:registration][:password]) 
=======
        @registration=Registration.new(:name => params[:registration][:name],:emailaddress => params[:registration]     [:emailaddress],:password => params[:registration][:password])
>>>>>>> d4fc60e117b8ca30feced9b7b2fa0a42c9712216
        respond_to do |format|
         if @registration.save
            format.html { redirect_to thanq_registrations_path }
        else
            format.html{render :action => "new"}
      
       end
    end
   else
<<<<<<< HEAD
         redirect_to registrations_path 
=======
       redirect_to registrations_path
>>>>>>> ecf37fb366ee78729309aa32f602dad18c435902
  end
   end

  def thanq
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'Update was successfully created.') }
       else
        format.html { render :action => "new" }
     end
  end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'Update was successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
  end

  def destroy
   @user = User.find(params[:id])
    @user.destroy
 redirect_to users_path
  end


end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrators/create.html.erb
<h1>Administrators#create</h1>
<p>Find me in app/views/administrators/create.html.erb</p>

app/views/administrators/delete.html.erb
<h1>Administrators#delete</h1>
<p>Find me in app/views/administrators/delete.html.erb</p>

app/views/administrators/flash.html.erb
<% flash.each do |key, msg| %>
<%=content_tag :div, msg, :class =>"flash_#{key}", :id => "app_flash"%>
<% end %>

app/views/administrators/index.html.erb
<h1>Administrators#index</h1>
<p>Find me in app/views/administrators/index.html.erb</p>

app/views/administrators/new.html.erb
<h1>Administrators#new</h1>
<p>Find me in app/views/administrators/new.html.erb</p>

<%= render 'flash' %>
<div align="center">

<%= form_for(@administrator) do |f|%>
  <%= f.label :Username %>
  <%= f.text_field :username %><br/>
<%= f.label :Password  %>
  <%= f.password_field :password %><br />
  <%= f.submit "Login" %><br /></br />
<% end %>

</div>

app/views/administrators/show.html.erb
<h1>Administrators#show</h1>
<p>Find me in app/views/administrators/show.html.erb</p>

app/views/home/index.html.erb
<<<<<<< HEAD

This is home page

=======
<<<<<<< HEAD
=======
<<<<<<< HEAD

=======
<<<<<<< HEAD
========
This is home page
========
=======
<<<<<<< HEAD
>>>>>>> 5a795c21f7d78d8f21c6bd2902535dd2cd76bfec
>>>>>>> d4fc60e117b8ca30feced9b7b2fa0a42c9712216
>>>>>>> 4e9b5ba0a5ca01fe8b9652b3b61c260fc54a0cc3
<div align="center"><%= form_for(:registration,:url => {:controller => "login", :action => "create"}) do |f|%>
<i style="color:green">Already A User  :</i>
<%= f.label :email %>
  <%= f.text_field :email %>
<%= f.label :Password  %>
  <%= f.password_field :password %>
  <%= f.submit "Login" %><br /></br />
<% end %></div>
<div align="right">
 <i style="font-size:20px">Do u Want To Register</i>
<<<<<<< HEAD
 <%= link_to "Register Now",new_registration_path %>

</div>

=======
<<<<<<< HEAD
 <%= link_to "Register Now",new_registration_path %> 
</div>
=======
 <%= link_to "Register Now",registrations_path %>
 
</div></br></br>
<div align="right">
<i style="font-size:20px">Users Bookmarks</i>
<%= link_to '@total_bookmarks.title' %>
</div>
<<<<<<< HEAD

=======
=======
<<<<<<< HEAD
This is home page
=======
hi how ru
>>>>>>> 33974ae8361aa7be140ed58d918681e684cebaa1
>>>>>>> 78e96ad409b22ad63c71ab33320580c4a5c00ca8
>>>>>>> 3271831d142430af27be10ac9d061af528258ffa
>>>>>>> 5a795c21f7d78d8f21c6bd2902535dd2cd76bfec
>>>>>>> d4fc60e117b8ca30feced9b7b2fa0a42c9712216
>>>>>>> 4e9b5ba0a5ca01fe8b9652b3b61c260fc54a0cc3

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= render 'administrators/flash' %>
<%= link_to 'Logout'%>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body  bgcolor="#F7F7F0">
<% flash.each do |key, msg| %>
    <%=content_tag :div, msg, :id =>"flash_#{key}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f|%>
  <%= f.label :UserName %>
  <%= f.text_field :name %><br/>
<%= f.label :Title %>
  <%= f.text_field :title %><br/>
<%= f.label :Description %>
  <%= f.text_field :description %><br/>
  <%= f.submit  %><br /></br />
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing News And Updates</h1>

<table >
  

<% @users.each do |users| %>
  <tr>
    <td><h4>Name</h4></td>
    <td><%= users.name %></td></tr>
<tr>
<td><h4>Title</h4></td>
    <td><%= link_to users.title , users.title , :target => :_blank %></td></tr>
<tr><td><h4>Description</h4></td>
    <td><%= users.description %></td></tr>
<tr>
    <td><%= link_to 'Show', users %></td>
    <td><%= link_to 'Edit', edit_user_path(users) %></td>
    <td><%= link_to 'Destroy', users, :confirm => 'Are you sure?', :method => :delete %></td></tr>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Update', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<b>Content : </b>
 <%= @user.name %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>